title: Incomplete thoughts
author:
    #name: 'human - machine'
    email: hello@hectornoval.com
description: "human - machine.\n"
show_excerpts: false
minima:
    date_format: '%Y %b'
social_links:
    twitter: hectornoval
    github: hectornoval
theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag
