title: Incomplete toughts
author:
    name: 'human - machine'
    email: your-email@domain.com
description: "describe el contenido.\n"
show_excerpts: false
minima:
    date_format: '%Y %b' 
social_links:
    twitter: jekyllrb
    github: jekyll
theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag
