title: Incomplete thoughts
author:
    #name: 'human - machine'
    email: hello@hectornoval.com
description: "human - machine\n"
show_excerpts: false
minima:
    date_format: '%Y %B '
es:
  date:
    #abbr_daynames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
    #daynames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
    #abbr_monthnames: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    monthnames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
social_links:
    twitter: hectornoval
    github: hectornoval
theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag
