title: Incomplete thoughts
author:
    #name: 'human - machine'
    email: hello@hectornoval.com
description: "human - machine\n"
show_excerpts: false
minima:
    date_format: '%Y %B '
    #twitter: hectornoval
    github: hectornoval
theme: minima
plugins:
    - jekyll-feed
    - jekyll-seo-tag
header_pages: #the pages that I want to publish in the header
  - log.md
  - biblio.md
